### PR TITLE
[homework#13]-envs-1 by Ilya Ischenko

### PR DESCRIPTION
**Pull request by ilya07092000**

### CODE REVIEW

**Comment by esvyridov** [comment]
Looks good. I would add `.gitignore` file with node_modules and the `dist` folder because anyone else who will work on that landing page potentially can add these folders to they commits

**Comment by ilya07092000** [comment]
> Looks good. I would add `.gitignore` file with node_modules and the `dist` folder because anyone else who will work on that landing page potentially can add these folders to they commits

We have .gitignore file with necessary config in root folder.

https://github.com/qaprosoft/devlaba01/blob/master/.gitignore

**Comment by ilya07092000** [comment]
> Looks good. I would add `.gitignore` file with node_modules and the `dist` folder because anyone else who will work on that landing page potentially can add these folders to they commits

Should i create my own .gitignore?

**Comment by esvyridov** [comment]
I see. Ok, that's fine than

**Review by esvyridov — APPROVED** [review]

**Pull request merged**
